AntonenkoFamilyServerFinances/Controllers/Web/BudgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DataLayer.Models;
using BusinessLayer.Interfaces;
using StructureMap;
using BusinessLayer.Entities;
using AutoMapper;
using System.Web.Security;
using AFinances.PresentationLayer.Infrastructure;

namespace AntonenkoFamilyServerFinances.Controllers.Web
{
    /// <summary>
    /// Контроллер страниц управления бюджетом
    /// </summary>
    [Authorize]
    public class BudgetController : Controller
    {
        /// <summary>
        /// Сервис управления ресурспаками
        /// </summary>
        private IResourcePackService resourcePackService;

        /// <summary>
        /// Сервис управления бюджетом
        /// </summary>
        private IBudgetService<IncomeRequestEntity> budgetService;

        /// <summary>
        /// Сервис управления ресурсами
        /// </summary>
        private IResourcesService resourcesService;

        /// <summary>
        /// Сервис управления группами пользователей
        /// </summary>
        private IUserGroupService userGroupService;

        /// <summary>
        /// Сервис управления прибылью
        /// </summary>
        private ICashFlowService<Income, IncomeRequestEntity> incomeService;

        /// <summary>
        /// Сервис управления затратами
        /// </summary>
        private ICashFlowService<Spending, SpendingRequestEntity> spendingService;

        /// <summary>
        /// Сервис типов ресурса
        /// </summary>
        private IBaseEntityService<ResourceType, ResourceTypeEntity> resourceTypeService;

        /// <summary>
        /// Базовый контроллер
        /// </summary>
        public BudgetController()
        {
            budgetService = ObjectFactory.GetInstance<IBudgetService<IncomeRequestEntity>>();
            resourcePackService = ObjectFactory.GetInstance<IResourcePackService>();
            resourcesService = ObjectFactory.GetInstance<IResourcesService>();
            userGroupService = ObjectFactory.GetInstance<IUserGroupService>();
            incomeService = ObjectFactory.GetInstance<ICashFlowService<Income, IncomeRequestEntity>>();
            spendingService = ObjectFactory.GetInstance<ICashFlowService<Spending, SpendingRequestEntity>>();
            resourceTypeService = ObjectFactory.GetInstance<IBaseEntityService<ResourceType, ResourceTypeEntity>>();
        }

        /// <summary>
        /// Страница просмотра бюджета
        /// </summary>
        /// <returns>Возвращает представление страницы просмотра бюджета</returns>
        [HttpGet]
        public ActionResult Index(){
            return View(Mapper.Map<IEnumerable<ResourcePackEntity>>(
                resourcePackService.GetForCurrentUserGroup(Membership.GetUser().UserName)));
        }

        /// <summary>
        /// Страница текущего бюджета ресурспаков
        /// </summary>
        /// <returns>Возвращает представление страницы текущего бюджета ресурспаков</returns>
        [HttpPost]
        public ActionResult GetCurrentBudget()
        {
            var currentBudget = budgetService.GetBudgetResourcePacks();
            return PartialView("Index_CurrentBudget", currentBudget);
        }

        /// <summary>
        /// Страница просмотра бюджета ресурспака на определенную дату
        /// </summary>
        /// <param name="date">Дата просмотра бюджета ресурспака</param>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <returns>Возвращает представление страницы просмотра бюджета ресурспака на определенную дату</returns>
        [HttpGet]
        public ActionResult ViewDateBudget(long resourcePackId, DateTime date)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePackId);
            var budget = budgetService.GetDailyBudgets(date, 1, resourcePackId).FirstOrDefault();
            var resourcePack = resourcePackService.FindById(resourcePackId);
            return View(new BudgetResourceEntity() {
                Date = date,
                ResourcePackId = resourcePackId,
                Balance = budget.Balance,
                ResourcePackName = resourcePack.Name,
                SummaryCredit = budget.SummaryCreditSum
            });
        }

        /// <summary>
        /// Страница добавления прибыли на определенную дату
        /// </summary>
        /// <param name="date">Дата добавления (оптимально)</param>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <returns>Возвращает представление страницы добавления прибыли на определенную дату</returns>
        [HttpGet]
        public ActionResult AddIncome(long resourcePackId, DateTime? date = null)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePackId);
            var resources = resourcesService.GetResourcePackResources(resourcePackId);
            var income = new IncomeRequestEntity() { Resources = resources };
            income.DateAndTime = date ?? DateTime.Today;
            return PartialView(income);
        }

        /// <summary>
        /// Добавляет прибыль в базу данных
        /// </summary>
        /// <param name="income">Сущность прибыли</param>
        /// <returns>Перенаправляет на страницу просмотра прибыли</returns>
        [HttpPost]
        public ActionResult AddIncome(IncomeRequestEntity income)
        {
            if (ModelState.IsValid)
            {
                AuthorizeHelper.AuthorizeUserGroupByResource(income.ResourceId);
                var id = incomeService.Add(income, Membership.GetUser().UserName);
                return RedirectToAction( "ViewIncome", new { id });
            }

            income.Resources = resourcesService.GetResourcePackResources(income.ResourcePackId);
            return PartialView(income);
        }

        /// <summary>
        /// Страница изменения определенной прибыли
        /// </summary>
        /// <param name="id">Идентификатор прибыли</param>
        /// <returns>Возвращает представление страницы изменения определенной прибыли</returns>
        [HttpGet]
        public ActionResult EditIncome(long id)
        {
            var income = Mapper.Map<IncomeRequestEntity>(incomeService.FindById(id));
            AuthorizeHelper.AuthorizeUserGroupByResource(income.ResourceId);
            var resource = resourcesService.FindById(income.ResourceId);
            income.Resources = resourcesService.GetResourcePackResources(resource.ResourcePackId);
            income.ResourcePackId = resource.ResourcePackId;
            return PartialView(Mapper.Map<IncomeRequestEntity>(income));
        }

        /// <summary>
        /// Изменяет определенный объект прибыли
        /// </summary>
        /// <param name="income">Сущность прибыли</param>
        /// <returns>Перенаправляет на страницу просмотра прибыли</returns>
        [HttpPost]
        public ActionResult EditIncome(IncomeRequestEntity income)
        {
            if (ModelState.IsValid)
            {
                AuthorizeHelper.AuthorizeUserGroupByResource(income.ResourceId);
                incomeService.Update(income, Membership.GetUser().UserName);
                return RedirectToAction(
                    "ViewIncome",
                    new { id = income.Id });
            }

            income.Resources = resourcesService.GetResourcePackResources(income.ResourcePackId);
            return PartialView(income);
        }

        /// <summary>
        /// Страница изменения определенного убытка
        /// </summary>
        /// <param name="id">Идентификатор расхода</param>
        /// <returns>Возвращает представление страницы изменения определенного убытка</returns>
        [HttpGet]
        public ActionResult EditSpending(long id)
        {
            var spending = Mapper.Map<SpendingRequestEntity>(spendingService.FindById(id));
            AuthorizeHelper.AuthorizeUserGroupByResource(spending.ResourceId);
            var resource = resourcesService.FindById(spending.ResourceId);
            spending.Resources = resourcesService.GetResourcePackResources(resource.ResourcePackId);
            spending.ResourcePackId = resource.ResourcePackId;
            return PartialView(Mapper.Map<SpendingRequestEntity>(spending));
        }

        /// <summary>
        /// Изменяет определенный объект убытка
        /// </summary>
        /// <param name="spending">Сущность расхода</param>
        /// <returns>Перенаправляет на страницу просмотра убытка</returns>
        [HttpPost]
        public ActionResult EditSpending(SpendingRequestEntity spending)
        {
            if (ModelState.IsValid)
            {
                AuthorizeHelper.AuthorizeUserGroupByResource(spending.ResourceId);
                spendingService.Update(spending, Membership.GetUser().UserName);
                return RedirectToAction(
                    "ViewSpending",
                    new { id = spending.Id });
            }

            spending.Resources = resourcesService.GetResourcePackResources(spending.ResourcePackId);
            return PartialView(spending);
        }

        /// <summary>
        /// Страница добавления расхода на определенную дату 
        /// </summary>
        /// <param name="date">Дата добавления (оптимально)</param>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <returns>Перенаправляет на страницу просмотра бюджета на определенную дату</returns>
        [HttpGet]
        public ActionResult AddSpending(long resourcePackId, DateTime? date = null)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePackId);
            var resources = resourcesService.GetResourcePackResources(resourcePackId);
            var spending = new SpendingRequestEntity() { Resources = resources };
            spending.DateAndTime = date ?? DateTime.Today;
            return PartialView(spending);
        }

        /// <summary>

AntonenkoFamilyServerFinances/Controllers/Web/CreditController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using BusinessLayer.Interfaces;
using StructureMap;
using BusinessLayer.Entities;
using AutoMapper;
using System.Web.Security;
using BusinessLayer.Resources;
using AFinances.PresentationLayer.Infrastructure;

namespace DataLayer.Controllers.Web
{
    /// <summary>
    /// Контроллер страниц управления кредитами
    /// </summary>
    [Authorize]
    public class CreditController : Controller
    {
        /// <summary>
        /// Сервис кредитов
        /// </summary>
        private ICreditService creditService;

        /// <summary>
        /// Сервис ресурспаков
        /// </summary>
        private IResourcePackService resourcePackService;

        /// <summary>
        /// Базовый конструктор
        /// </summary>
        public CreditController()
        {
            creditService = ObjectFactory.GetInstance<ICreditService>();
            resourcePackService = ObjectFactory.GetInstance<IResourcePackService>();
        }

        /// <summary>
        /// Страница просмотра кредита
        /// </summary>
        /// <param name="id">Идентификатор кредита</param>
        /// <returns>Перенаправляет на страницу просмотра кредита</returns>
        [HttpGet]
        public ActionResult ViewCredit(long id)
        {
            var credit = Mapper.Map<CreditRequestEntity>(creditService.FindByIdWithRelatedData(id));
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(credit.ResourcePackId);
            return PartialView(credit);
        }

        /// <summary>
        /// Страница добавления кредита
        /// </summary>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <returns>Перенаправляет на страницу добавления кредита</returns>
        [HttpGet]
        public ActionResult AddCredit(long resourcePackId)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePackId);
            var credit = new CreditRequestEntity() { ResourcePackId = resourcePackId, StartDate = DateTime.Today, EndDate = DateTime.Today.AddMonths(1) };
            credit.ResourcePacks = resourcePackService
                .GetUserGroupResourcePacks(resourcePackService.FindById(resourcePackId).UserGroupId);
            return PartialView(credit);
        }

        /// <summary>
        /// Добавляет кредит в базу данных
        /// </summary>
        /// <param name="credit">Сущность кредита</param>
        /// <returns>Перенаправляет на страницу просмотра кредита</returns>
        [HttpPost]
        public ActionResult AddCredit(CreditRequestEntity credit)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(credit.ResourcePackId);
            if (ModelState.IsValid)
            {
                var id = creditService.Add(credit, Membership.GetUser().UserName);
                return RedirectToAction("ViewCredit", new { id });
            }

            credit.ResourcePacks = resourcePackService
                .GetUserGroupResourcePacks(resourcePackService.FindById(credit.ResourcePackId).UserGroupId);
            return PartialView(credit);
        }

        /// <summary>
        /// Страница изменения кредита
        /// </summary>
        /// <param name="id">Идентификатор кредита</param>
        /// <returns>Перенаправляет на страницу изменения кредита</returns>
        [HttpGet]
        public ActionResult EditCredit(long id)
        {
            var credit = Mapper.Map<CreditRequestEntity>(creditService.FindByIdWithRelatedData(id));
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(credit.ResourcePackId);
            credit.ResourcePacks = resourcePackService
                .GetUserGroupResourcePacks(credit.ResourcePack.UserGroupId);
            return PartialView(credit);
        }

        /// <summary>
        /// Изменяет кредит и обновляет его в базе данных
        /// </summary>
        /// <param name="credit">Сущность кредита</param>
        /// <returns>Перенаправляет на страницу просмотра кредита</returns>
        [HttpPost]
        public ActionResult EditCredit(CreditRequestEntity credit)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(credit.ResourcePackId);
            var dbCredit = creditService.FindByIdWithRelatedData(credit.Id);
            var resourcePack = resourcePackService.FindById(credit.ResourcePackId);
            if (resourcePack.UserGroupId != dbCredit.ResourcePack.UserGroupId)
            {
                ModelState.AddModelError(string.Empty, Errors.CantChangeUserGroup);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    creditService.Update(credit, Membership.GetUser().UserName);
                    return RedirectToAction("ViewCredit", new { id = credit.Id });
                }
            }

            credit.ResourcePacks = resourcePackService.GetUserGroupResourcePacks(dbCredit.ResourcePack.UserGroupId);
            return PartialView(credit);
        }

        /// <summary>
        /// Удаляет кредит из базы данных
        /// </summary>
        /// <param name="id">Идентификатор кредита</param>
        /// <returns>Перенаправляет на пустую страницу модального окна</returns>
        [HttpGet]
        public ActionResult RemoveCredit(long id)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(creditService.FindById(id).ResourcePackId);
            creditService.Remove(id, Membership.GetUser().UserName);
            return PartialView("_BlankModalForm");
        }

        /// <summary>
        /// Выставляет флаг 'IsPayed' кредиту и меняет дату окончания на текущую
        /// </summary>
        /// <param name="id">Идентификатор кредита</param>
        /// <returns>Перенаправляет на страницу просмотра кредита</returns>
        [HttpGet]
        public ActionResult CloseCredit(long id)
        {
            var credit = Mapper.Map<CreditRequestEntity>(creditService.FindByIdWithRelatedData(id));
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(credit.ResourcePackId);
            if (credit.StartDate >= DateTime.Today.AddDays(1))
            {
                ModelState.AddModelError(string.Empty, Errors.CloseCreditStartDateMoreThanNow);
                return PartialView("ViewCredit", credit);
            }
            else
            {
                creditService.CloseCredit(id, Membership.GetUser().UserName);
                return RedirectToAction("ViewCredit", new { id });
            }
        }
    }
}

AntonenkoFamilyServerFinances/Views/Budget/AddIncome.cshtml
@using AFinances.PresentationLayer.Resources.Views
@model BusinessLayer.Entities.IncomeRequestEntity
@{
    ViewBag.Title = Titles.AddIncome;
    ViewBag.AcceptBtnName = Common.Add;
}

@Html.Partial("AddEditIncomeSpendingBase")

AntonenkoFamilyServerFinances/Views/Budget/Index.cshtml
@using BusinessLayer.Entities
@using DataLayer
@using AFinances.PresentationLayer.Resources.Views
@model IEnumerable<ResourcePackEntity>
@{
    ViewBag.Title = Titles.ViewBudget;
}
<div id="ViewBudgetForm">
    @Html.Partial("Index_Chart")
    @Html.Partial("Index_CurrentBudget", new BudgetResourcePackEntity[0])
    <br />
    @Html.Partial("Index_BudgetHistory")
</div>

<script type="text/basis-template" id="budget-row">
<tr>
    <td> <a href="{url}">{date}</a> </td>
    <td> {balance} </td>
    <td> <span class="text-danger"> {creditSum} </span> </td>
    <td> {total} </td>
    <td> <table class="credits"> {credits} </table> </td>
</tr>
</script>

<script type="text/basis-template" id="credit-row">
<tr class="panel panel-default">
    <td class="credit-name-col"> <a class="modal-redirect" url="@Url.Action("ViewCredit","Credit")/{id}" href="@Constants.FakeLinkUrl"> {name} </a> </td>
    <td> {from} - {to} </td>
    <td> <span class="text-danger"> {summ} </span> </td>
</tr>
</script>

<script>
    var firstSelectedResourcePack = getCurrentResourcePackId() || @(Model.Any() ? (long?)Model.First().Id : null);
    $("#CurrentBudgetForm").submit();
    var viewBudgetFunctions = new ViewBudget(
    "@DataLayer.Constants.MomentDateFormat",
    firstSelectedResourcePack,
    "@DataLayer.Constants.MomentServerDateFormat",
    "@Common.Time",
    "@Common.Budget",
    "@Common.Month",
    "@Common.Rubles",
    '@Common.ShowAll',
    '@Common.HideAll');

    viewBudgetFunctions.DropdownsSelectResourcePack(firstSelectedResourcePack);
    $("#@Constants.ModalPanelId").on('hidden.bs.modal', function () {
        viewBudgetFunctions.UpdateResourcePackPanels();
        viewBudgetFunctions.UpdateChart();
        viewBudgetFunctions.UpdateList();
        $("#CurrentBudgetForm").submit();
    });

    $(document).ready(function () {
        viewBudgetFunctions.UpdateChart();
        viewBudgetFunctions.UpdateList();
        $(".outputmodebtns").children().click(function () { viewBudgetFunctions.SelectOutputMode(this); });
        $('#chartFilter').find('[name=okPanel]').click(function () { viewBudgetFunctions.LoadChartData(); });
        $('#listFilter').find('[name=okPanel]').click(function () { viewBudgetFunctions.LoadListData(); });
        $('#chartFilter').find('[name=prevPanel]').click(function () { viewBudgetFunctions.PrevNextChart(false); });
        $('#chartFilter').find('[name=nextPanel]').click(function () { viewBudgetFunctions.PrevNextChart(true); });
        $('#listFilter').find('[name=prevPanel]').click(function () { viewBudgetFunctions.PrevNextList(false); });
        $('#listFilter').find('[name=nextPanel]').click(function () { viewBudgetFunctions.PrevNextList(true); });
        $(".element-counter").TouchSpin({
            min: 2,
            max: 24,
            boostat: 5,
            maxboostedstep: 10
        });
    });
</script>

AntonenkoFamilyServerFinances/Views/Budget/Index_CurrentBudget.cshtml
@using AFinances.PresentationLayer.Resources.Views.Budget
@using AFinances.PresentationLayer.Resources.Views
@using BusinessLayer.Entities
@using DataLayer
@model IEnumerable<BudgetResourcePackEntity>
<div id="CurrentBudgetBase">
    @using (Ajax.BeginForm(
        null,
        null,
        new AjaxOptions
        {
            UpdateTargetId = "CurrentBudgetBase",
            LoadingElementId = "CurrentBudgetLoader",
            Url = Url.Action("GetCurrentBudget"),
            OnSuccess = "viewBudgetFunctions.BindCurrentBudgetPanelEvents()"
        },
        new { id = "CurrentBudgetForm" }))
    {  
    <div class="base-form">
        <div class="base-form-heading">
            <h3>@Index.CurrentBudget</h3>
            <div id="CurrentBudgetLoader" class="loader loader-default inner-loader"></div>
            <div class="horizontal-autoscroll">
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th>@Common.ResourcePack</th>
                        <th>@Index.TotalAmount</th>
                        <th>@Index.CreditsAmount</th>
                        <th>@Index.FullAmount</th>
                        <th>@Index.Credits <button type="button" class="btn btn-default" id="ToggleAllCurrentCredits">@Common.ShowAll</button></th>
                    </tr>
                    </thead>
                    <tbody>
                            @foreach (var item in Model ?? new BudgetResourcePackEntity[0])
                            {
                                <tr>
                                    <td><a href="@Url.Action("ViewResourcePack", "Resource", new { id = item.ResourcePackId })">@item.ResourcePackName</a></td>
                                    <td>@Math.Round(item.Balance, Constants.MoneyDecimalPlaces)@Common.Rubles</td>
                                    <td class="text-danger">@Math.Round(item.SummaryCredit, Constants.MoneyDecimalPlaces)@Common.Rubles</td>
                                    <td>@Math.Round((item.Balance - item.SummaryCredit), Constants.MoneyDecimalPlaces)@Common.Rubles</td>
                                    <td>
                                        @foreach (var credit in item.Credits)
                                        {
                                            <div class="panel panel-default current-credit-panel">
                                                <div class="panel-heading @(credit.IsPayed ? Html.Raw("payed-credit") : Html.Raw("not-payed-credit"))">
                                                    <h4 class='panel-title'>
                                                        <a class="modal-redirect" url="@Url.Action("ViewCredit", "Credit", new { id = credit.Id })" href="@Constants.FakeLinkUrl">@credit.Name</a>
                                                        <span class="italic-text">
                                                            <span class="append-colon">(@Index.State</span>
                                                            @(!credit.IsPayed ? Index.Opened : Index.Closed))
                                                        </span>
                                                    </h4>
                                                </div>
                                                <div class="panel-body">
                                                    @credit.StartDate.ToShortDateString()-@credit.EndDate.ToShortDateString()
                                                </div>
                                                <div class='panel-footer'>@Math.Round(credit.Summ, Constants.MoneyDecimalPlaces)@Common.Rubles</div>
                                            </div>
                                        }
                                    </td>
                                </tr>
                            }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    }
</div>
<script>
    initializeSpinner($("#CurrentBudgetLoader"));
</script>

AntonenkoFamilyServerFinances/Views/Budget/ViewDateBudget.cshtml
@using BusinessLayer.Entities
@using AFinances.PresentationLayer.Resources.Views
@using AFinances.PresentationLayer.Resources.Views.Budget
@using DataLayer
@model BudgetResourceEntity
@{
    ViewBag.Title = Titles.ViewBudget;
    const string ModalPanelSelector = "#" + Constants.ModalPanelId;
}

<div class="base-form" id="ViewDateBudgetForm">
    <div class="base-form-heading">
        <h3>
            <button class="btn btn-default next-prev-btn" id="PrevDate">&lt;</button>
            @ViewDateBudget.ViewBudgetOn <span id="DateText">@Model.Date.ToString(Constants.DisplayDateFormat)</span>
            <button class="btn btn-default next-prev-btn" id="NextDate">&gt;</button>
        </h3>
        <br/>
        <label class="append-colon">@Common.ResourcePack</label>@Model.ResourcePackName
        <br/>
        <label class="append-colon">@Common.Resource</label>
        <select class="form-control resource-dropdown" id="ResourceId"></select>
        <br/>
        <label class="append-colon">@ViewDateBudget.ResourcePacksCreditsAmount</label><span id="SummaryCredit">@Math.Round(Model.SummaryCredit, Constants.MoneyDecimalPlaces)</span> @Common.Rubles
    </div>
</div>
<br/>
<div class="row cols-container">
    <div class="col-md-4"></div>
    <div class="col-md-4 text-center">
        <div class="base-form">
            <div class="base-form-heading">
                <h1><span id="Balance">@Math.Round((Model.Balance - Model.SummaryCredit), Constants.MoneyDecimalPlaces)</span> @Common.Rubles</h1>
            </div>
        </div>
    </div>
</div>
<br/>
<div class="row cols-container">
    <div class="col-md-6">
        @Html.Partial("ListPanel", new[] { ViewDateBudget.Income, "Incomes", "AddIncome" })
    </div>
    <div class="col-md-6">
        @Html.Partial("ListPanel", new[] { ViewDateBudget.Spendings, "Spendings", "AddSpending" })
    </div>
</div>
<br/>
<div class="row cols-container">
    <div class="col-md-6">
        @Html.Partial("ListPanel", new[] { ViewDateBudget.Credits, "Credits", "AddCredit" })
    </div>
    <div class="col-md-6">
        @Html.Partial("ListPanel", new[] { ViewDateBudget.MandatoryCashOffs, "MandatoryCashOffs", "AddMandatoryCashOff" })
    </div>
</div>
<script>
    $('@ModalPanelSelector').modal({show : false});

    var viewDateBudgetFunctions = new ViewDateBudget(
        @Model.ResourcePackId,
        "@Model.Date.ToString(DataLayer.Constants.JavascriptDateFormat)",
        "@DataLayer.Constants.MomentDateFormat",
        "@DataLayer.Constants.MomentServerDateFormat",
        "@Url.Action("ViewSpending", "Budget")",
        "@Url.Action("ViewIncome", "Budget")",
        "@Url.Action("ViewDateBudget", "Budget")",
        "@Url.Action("ViewCredit", "Credit")",
        "@Url.Action("ViewMandatoryCashOff", "MandatoryCashOff")",
        "@Common.Rubles",
        "@Common.All");

    $(document).ready(function() {
        viewDateBudgetFunctions.fillResourcePackResources();
        viewDateBudgetFunctions.reloadData();
    });

    $("@ModalPanelSelector").on('hidden.bs.modal', function () {
        viewDateBudgetFunctions.updateCurrentResourcePack();
        viewDateBudgetFunctions.updateModel();
    });

    var commonAddElementUrlTemplate = "{0}?resourcePackId=@(Model.ResourcePackId)&date={1}";
    $("#AddIncome").click(function() { showAndRedirectModal(commonAddElementUrlTemplate.format('@(Url.Action("AddIncome", "Budget"))', getFormattedCurrentDate()))});
    $("#AddSpending").click(function() { showAndRedirectModal(commonAddElementUrlTemplate.format('@(Url.Action("AddSpending", "Budget"))', getFormattedCurrentDate()))});
    $("#AddCredit").click(function() { showAndRedirectModal(commonAddElementUrlTemplate.format('@(Url.Action("AddCredit", "Credit"))', getFormattedCurrentDate()))});
    $("#AddMandatoryCashOff").click(function() { showAndRedirectModal(commonAddElementUrlTemplate.format('@(Url.Action("AddMandatoryCashOff", "MandatoryCashOff"))', getFormattedCurrentDate()))});

    function getFormattedCurrentDate() {
        return moment(viewDateBudgetFunctions.currentDate).format(viewDateBudgetFunctions.serverDateFormat);
    }

    $("#ResourceId").change(function() { viewDateBudgetFunctions.reloadData(); });
    $("#PrevDate").click(function() { viewDateBudgetFunctions.setPreviousDate() });
    $("#NextDate").click(function() { viewDateBudgetFunctions.setNextDate() });
</script>

AntonenkoFamilyServerFinances/Views/Budget/ViewIncome.cshtml
@using AFinances.PresentationLayer.Resources.Views
@model BusinessLayer.Entities.IncomeRequestEntity

@{
    ViewBag.Title = Titles.ViewIncome;
}

@Html.Partial("ViewIncomeSpendingBase")

<script>
    $("#ChangeMoneyTurnover").attr("url","@Url.Action("EditIncome", new { id = Model.Id })");

    function removeMoneyTurnover(){
        $("#dialog-confirm").dialog("close");
        modalPanelFunctions.redirectModal("@Url.Action("RemoveIncome", "Budget", new { id = Model.Id })");
    }
</script>