AntonenkoFamilyServerFinances/Controllers/Web/MandatoryCashOffController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using BusinessLayer.Interfaces;
using StructureMap;
using AutoMapper;
using BusinessLayer.Entities;
using System.Web.Security;
using AFinances.PresentationLayer.Infrastructure;
using BusinessLayer.Resources;

namespace AntonenkoFamilyServerFinances.Controllers.Web
{
    /// <summary>
    /// Контроллер страниц управления запланированными обязательными платежами
    /// </summary>
    [Authorize]
    public class MandatoryCashOffController : Controller
    {
        /// <summary>
        /// Сервис обязательных платежей
        /// </summary>
        private IMandatoryCashOffService mandatoryCashOffService;

        /// <summary>
        /// Сервис ресурспаков
        /// </summary>
        private IResourcePackService resourcePackService;

        /// <summary>
        /// Базовый конструктор
        /// </summary>
        public MandatoryCashOffController()
        {
            mandatoryCashOffService = ObjectFactory.GetInstance<IMandatoryCashOffService>();
            resourcePackService = ObjectFactory.GetInstance<IResourcePackService>();
        }

        /// <summary>
        /// Страница просмотра обязательного платежа
        /// </summary>
        /// <param name="id">Идентификатор обязательного платежа</param>
        /// <returns>Перенаправляет на страницу просмотра обязательного платежа</returns>
        [HttpGet]
        public ActionResult ViewMandatoryCashOff(long id)
        {
            var mandatoryCashOff = Mapper.Map<MandatoryCashOffEntity>(mandatoryCashOffService.FindByIdWithRelatedData(id));
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(mandatoryCashOff.ResourcePackId);
            return PartialView(mandatoryCashOff);
        }

        /// <summary>
        /// Страница добавления обязательного платежа
        /// </summary>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <param name="date">Дата обязательного платежа (оптимально)</param>
        /// <returns>Перенаправляет на страницу добавления обязательного платежа</returns>
        [HttpGet]
        public ActionResult AddMandatoryCashOff(long resourcePackId, DateTime? date = null)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePackId);
            var mandatoryCashOff = new MandatoryCashOffEntity() { ResourcePackId = resourcePackId };
            mandatoryCashOff.DateAndTime = date ?? DateTime.Today;
            mandatoryCashOff.ResourcePacks = resourcePackService
                .GetUserGroupResourcePacks(resourcePackService.FindById(resourcePackId).UserGroupId);
            return PartialView(mandatoryCashOff);
        }

        /// <summary>
        /// Добавляет обязательный платеж в базу данных
        /// </summary>
        /// <param name="credit">Сущность обязательного платежа</param>
        /// <returns>Перенаправляет на страницу просмотра обязательного платежа</returns>
        [HttpPost]
        public ActionResult AddMandatoryCashOff(MandatoryCashOffEntity mandatoryCashOff)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(mandatoryCashOff.ResourcePackId);
            if (ModelState.IsValid)
            {
                var id = mandatoryCashOffService.Add(mandatoryCashOff, Membership.GetUser().UserName);
                return RedirectToAction("ViewMandatoryCashOff", new { id });
            }

            mandatoryCashOff.ResourcePacks = resourcePackService
                .GetUserGroupResourcePacks(resourcePackService.FindById(mandatoryCashOff.ResourcePackId).UserGroupId);
            return PartialView(mandatoryCashOff);
        }

        /// <summary>
        /// Страница изменения обязательного платежа
        /// </summary>
        /// <param name="id">Идентификатор обязательного платежа</param>
        /// <returns>Перенаправляет на страницу изменения обязательного платежа</returns>
        [HttpGet]
        public ActionResult EditMandatoryCashOff(long id)
        {
            var mandatoryCashOff = Mapper.Map<MandatoryCashOffEntity>(mandatoryCashOffService.FindByIdWithRelatedData(id));
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(mandatoryCashOff.ResourcePackId);
            mandatoryCashOff.ResourcePacks = resourcePackService
                .GetUserGroupResourcePacks(mandatoryCashOff.ResourcePack.UserGroupId);
            return PartialView(mandatoryCashOff);
        }

        /// <summary>
        /// Изменяет обязательный платеж и обновляет его в базе данных
        /// </summary>
        /// <param name="credit">Сущность обязательного платежа</param>
        /// <returns>Перенаправляет на страницу просмотра обязательного платежа</returns>
        [HttpPost]
        public ActionResult EditMandatoryCashOff(MandatoryCashOffEntity mandatoryCashOff)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(mandatoryCashOff.ResourcePackId);
            var dbMandatoryCashOff = mandatoryCashOffService.FindByIdWithRelatedData(mandatoryCashOff.Id);
            var resourcePack = resourcePackService.FindById(mandatoryCashOff.ResourcePackId);

            if (resourcePack.UserGroupId != dbMandatoryCashOff.ResourcePack.UserGroupId)
            {
                ModelState.AddModelError(string.Empty, Errors.CantChangeUserGroup);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    mandatoryCashOffService.Update(mandatoryCashOff, Membership.GetUser().UserName);
                    return RedirectToAction("ViewMandatoryCashOff", new { id = mandatoryCashOff.Id });
                }
            }

            mandatoryCashOff.ResourcePacks = resourcePackService
                .GetUserGroupResourcePacks(dbMandatoryCashOff.ResourcePack.UserGroupId);
            return PartialView(mandatoryCashOff);
        }

        /// <summary>
        /// Удаляет обязательный платеж из базы данных
        /// </summary>
        /// <param name="id">Идентификатор обязательного платежа</param>
        /// <returns>Перенаправляет на пустую страницу модального окна</returns>
        [HttpGet]
        public ActionResult RemoveMandatoryCashOff(long id)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(mandatoryCashOffService.FindById(id).ResourcePackId);
            mandatoryCashOffService.Remove(id, Membership.GetUser().UserName);
            return PartialView("_BlankModalForm");
        }
    }
}

AntonenkoFamilyServerFinances/Views/MandatoryCashOff/AddEditMandatoryCashOffBase.cshtml
@using BusinessLayer.Infrastructure
@using DataLayer
@model BusinessLayer.Entities.MandatoryCashOffEntity
<div id="AddEditMandatoryCashOffBase">
    @using (Ajax.BeginForm(
        new AjaxOptions
        {
            UpdateTargetId = "AddEditMandatoryCashOffBase",
            LoadingElementId = "Loader",
            OnBegin = "modalPanelFunctions.toggleForm(true)",
            OnSuccess = "modalPanelFunctions.toggleForm(false)"
        }))
    {
        <div id="Loader" class="loader loader-default inner-loader"></div>
        <div class="base-form">
            <div class="base-form-heading">
                <h3>@ViewBag.Title</h3>
                @Html.HiddenFor(model => model.Id)
                @Html.ValidationSummary(true)
        <div class="editor-label">
            @Html.LabelFor(model => model.ResourcePackId)
        </div>
        <div class="editor-field">
            <select class="form-control" name="@CommonHelper.nameof(() => Model.ResourcePackId)">
                @foreach (var item in Model.ResourcePacks)
                { 
                    <option value="@item.Id" @if (Model.ResourcePackId == item.Id)
                                                {@Html.Raw("selected=\"selected\"")}>@item.Name </option>
                }
            </select>
            @Html.ValidationMessageFor(model => model.ResourcePackId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateAndTime)
        </div>
        <div class="editor-field">
            @Html.TextBox(
                CommonHelper.nameof(() => Model.DateAndTime),
                Model.DateAndTime.ToString(DataLayer.Constants.DisplayDateFormat),
                new { @class = "form-control datepicker" })
            @Html.ValidationMessageFor(model => model.DateAndTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Place)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Place, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Place)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Summ)
        </div>
        <div class="editor-field">
            @Html.TextBox(
                    CommonHelper.nameof(() => Model.Summ),
                    Model.Summ.ToString(new System.Globalization.CultureInfo(Constants.DateTimePickerCulture)),
                    new { @class = "z-index-zero" })
            @Html.ValidationMessageFor(model => model.Summ)
        </div>
        <br />
        <button type="submit" class="btn1 btn-1 btn-1b form-control">@ViewBag.AcceptBtnName</button>
    </div>
    </div>
}
</div>
<script>
    modalPanelFunctions.initializeModal();
    fixJQueryValidator();
    $("#Summ").TouchSpin({
        decimals: 2,
        min: 0.00,
        max: 1000000.00,
        boostat: 5,
        step: 0.01,
        maxboostedstep: 25
    });

    $('#AddEditMandatoryCashOffBase form').submit(function () {
        if ($('#AddEditMandatoryCashOffBase form').valid()) {
            fixFloatingDot("#Summ");
            $('#AddEditMandatoryCashOffBase form').validate().cancelSubmit = true;
        }
    });
</script>

AntonenkoFamilyServerFinances/Views/MandatoryCashOff/AddMandatoryCashOff.cshtml
@using AFinances.PresentationLayer.Resources.Views;
@{
    Layout = null;
    ViewBag.Title = Titles.AddMandatoryCashOff;
    ViewBag.AcceptBtnName = Common.Add;
}
@model BusinessLayer.Entities.MandatoryCashOffEntity
@Html.Partial("AddEditMandatoryCashOffBase")

AntonenkoFamilyServerFinances/Views/MandatoryCashOff/EditMandatoryCashOff.cshtml
@using AFinances.PresentationLayer.Resources.Views;
@{
    Layout = null;
    ViewBag.Title = Titles.EditMandatoryCashOff;
    ViewBag.AcceptBtnName = Common.Edit;
}
@model BusinessLayer.Entities.MandatoryCashOffEntity
@Html.Partial("AddEditMandatoryCashOffBase")

AntonenkoFamilyServerFinances/Views/MandatoryCashOff/ViewMandatoryCashOff.cshtml
@model BusinessLayer.Entities.MandatoryCashOffEntity
@using AFinances.PresentationLayer.Resources.Views;
@{
    ViewBag.Title = Titles.ViewMandatoryCashOff;
    Layout = null;
}
<div id="ViewMandatoryCashOffBase">
    @using (Ajax.BeginForm(new AjaxOptions {
        UpdateTargetId = "ViewMandatoryCashOffBase",
        LoadingElementId = "Loader",
        OnBegin="modalPanelFunctions.toggleForm(true)",
        OnSuccess="modalPanelFunctions.toggleForm(false)" }))
    {  
        @Html.HiddenFor(x => x.Id)
        <div id="Loader" class="loader loader-default inner-loader">
        </div>
        <div class="base-form">
            <div class="base-form-heading">
                <h3>@ViewBag.Title</h3>
                <label class="append-colon">@Html.LabelFor(model => model.DateAndTime)</label>
                @Model.DateAndTime
                <hr />
                <label class="append-colon">@Html.LabelFor(x => x.Description)</label>
                @Model.Description
                <hr />
                <label class="append-colon">@Html.LabelFor(x => x.Place)</label>
                @Model.Place
                <hr />
                <label class="append-colon">@Html.LabelFor(x => x.ResourcePackId)</label>
                @Model.ResourcePack.Name
                <hr />
                <label class="append-colon">@Html.LabelFor(x => x.Summ)</label>
                @Model.Summ@Common.Rubles
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <button type="button" class="btn1 btn-1 btn-1b form-control modal-redirect" url="@Url.Action("EditMandatoryCashOff", new { resourceId = Model.Id })">
                        @Common.Edit
                    </button>
                </div>
                <div class="col-xs-6">
                    <button type="button" class="btn1 btn-1 btn-1b form-control" id="RemoveMandatoryCashOff">
                        @Common.Remove
                    </button>
                </div>
            </div>
        </div>
    }
</div>
<script>
    modalPanelFunctions.initializeModal();
    $("#RemoveMandatoryCashOff").click(function () { toggleDialog(true); });

    function confirmDialog() {
                toggleDialog(false);
                modalPanelFunctions.redirectModal("@Url.Action("RemoveMandatoryCashOff", "MandatoryCashOff", new { id = Model.Id })");
    }
</script>