AntonenkoFamilyServerFinances/Controllers/Web/BudgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DataLayer.Models;
using BusinessLayer.Interfaces;
using StructureMap;
using BusinessLayer.Entities;
using AutoMapper;
using System.Web.Security;
using AFinances.PresentationLayer.Infrastructure;

namespace AntonenkoFamilyServerFinances.Controllers.Web
{
    /// <summary>
    /// Контроллер страниц управления бюджетом
    /// </summary>
    [Authorize]
    public class BudgetController : Controller
    {
        /// <summary>
        /// Сервис управления ресурспаками
        /// </summary>
        private IResourcePackService resourcePackService;

        /// <summary>
        /// Сервис управления бюджетом
        /// </summary>
        private IBudgetService<IncomeRequestEntity> budgetService;

        /// <summary>
        /// Сервис управления ресурсами
        /// </summary>
        private IResourcesService resourcesService;

        /// <summary>
        /// Сервис управления группами пользователей
        /// </summary>
        private IUserGroupService userGroupService;

        /// <summary>
        /// Сервис управления прибылью
        /// </summary>
        private ICashFlowService<Income, IncomeRequestEntity> incomeService;

        /// <summary>
        /// Сервис управления затратами
        /// </summary>
        private ICashFlowService<Spending, SpendingRequestEntity> spendingService;

        /// <summary>
        /// Сервис типов ресурса
        /// </summary>
        private IBaseEntityService<ResourceType, ResourceTypeEntity> resourceTypeService;

        /// <summary>
        /// Базовый контроллер
        /// </summary>
        public BudgetController()
        {
            budgetService = ObjectFactory.GetInstance<IBudgetService<IncomeRequestEntity>>();
            resourcePackService = ObjectFactory.GetInstance<IResourcePackService>();
            resourcesService = ObjectFactory.GetInstance<IResourcesService>();
            userGroupService = ObjectFactory.GetInstance<IUserGroupService>();
            incomeService = ObjectFactory.GetInstance<ICashFlowService<Income, IncomeRequestEntity>>();
            spendingService = ObjectFactory.GetInstance<ICashFlowService<Spending, SpendingRequestEntity>>();
            resourceTypeService = ObjectFactory.GetInstance<IBaseEntityService<ResourceType, ResourceTypeEntity>>();
        }

        /// <summary>
        /// Страница просмотра бюджета
        /// </summary>
        /// <returns>Возвращает представление страницы просмотра бюджета</returns>
        [HttpGet]
        public ActionResult Index(){
            return View(Mapper.Map<IEnumerable<ResourcePackEntity>>(
                resourcePackService.GetForCurrentUserGroup(Membership.GetUser().UserName)));
        }

        /// <summary>
        /// Страница текущего бюджета ресурспаков
        /// </summary>
        /// <returns>Возвращает представление страницы текущего бюджета ресурспаков</returns>
        [HttpPost]
        public ActionResult GetCurrentBudget()
        {
            var currentBudget = budgetService.GetBudgetResourcePacks();
            return PartialView("Index_CurrentBudget", currentBudget);
        }

        /// <summary>
        /// Страница просмотра бюджета ресурспака на определенную дату
        /// </summary>
        /// <param name="date">Дата просмотра бюджета ресурспака</param>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <returns>Возвращает представление страницы просмотра бюджета ресурспака на определенную дату</returns>
        [HttpGet]
        public ActionResult ViewDateBudget(long resourcePackId, DateTime date)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePackId);
            var budget = budgetService.GetDailyBudgets(date, 1, resourcePackId).FirstOrDefault();
            var resourcePack = resourcePackService.FindById(resourcePackId);
            return View(new BudgetResourceEntity() {
                Date = date,
                ResourcePackId = resourcePackId,
                Balance = budget.Balance,
                ResourcePackName = resourcePack.Name,
                SummaryCredit = budget.SummaryCreditSum
            });
        }

        /// <summary>
        /// Страница добавления прибыли на определенную дату
        /// </summary>
        /// <param name="date">Дата добавления (оптимально)</param>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <returns>Возвращает представление страницы добавления прибыли на определенную дату</returns>
        [HttpGet]
        public ActionResult AddIncome(long resourcePackId, DateTime? date = null)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePackId);
            var resources = resourcesService.GetResourcePackResources(resourcePackId);
            var income = new IncomeRequestEntity() { Resources = resources };
            income.DateAndTime = date ?? DateTime.Today;
            return PartialView(income);
        }

        /// <summary>
        /// Добавляет прибыль в базу данных
        /// </summary>
        /// <param name="income">Сущность прибыли</param>
        /// <returns>Перенаправляет на страницу просмотра прибыли</returns>
        [HttpPost]
        public ActionResult AddIncome(IncomeRequestEntity income)
        {
            if (ModelState.IsValid)
            {
                AuthorizeHelper.AuthorizeUserGroupByResource(income.ResourceId);
                var id = incomeService.Add(income, Membership.GetUser().UserName);
                return RedirectToAction( "ViewIncome", new { id });
            }

            income.Resources = resourcesService.GetResourcePackResources(income.ResourcePackId);
            return PartialView(income);
        }

        /// <summary>
        /// Страница изменения определенной прибыли
        /// </summary>
        /// <param name="id">Идентификатор прибыли</param>
        /// <returns>Возвращает представление страницы изменения определенной прибыли</returns>
        [HttpGet]
        public ActionResult EditIncome(long id)
        {
            var income = Mapper.Map<IncomeRequestEntity>(incomeService.FindById(id));
            AuthorizeHelper.AuthorizeUserGroupByResource(income.ResourceId);
            var resource = resourcesService.FindById(income.ResourceId);
            income.Resources = resourcesService.GetResourcePackResources(resource.ResourcePackId);
            income.ResourcePackId = resource.ResourcePackId;
            return PartialView(Mapper.Map<IncomeRequestEntity>(income));
        }

        /// <summary>
        /// Изменяет определенный объект прибыли
        /// </summary>
        /// <param name="income">Сущность прибыли</param>
        /// <returns>Перенаправляет на страницу просмотра прибыли</returns>
        [HttpPost]
        public ActionResult EditIncome(IncomeRequestEntity income)
        {
            if (ModelState.IsValid)
            {
                AuthorizeHelper.AuthorizeUserGroupByResource(income.ResourceId);
                incomeService.Update(income, Membership.GetUser().UserName);
                return RedirectToAction(
                    "ViewIncome",
                    new { id = income.Id });
            }

            income.Resources = resourcesService.GetResourcePackResources(income.ResourcePackId);
            return PartialView(income);
        }

        /// <summary>
        /// Страница изменения определенного убытка
        /// </summary>
        /// <param name="id">Идентификатор расхода</param>
        /// <returns>Возвращает представление страницы изменения определенного убытка</returns>
        [HttpGet]
        public ActionResult EditSpending(long id)
        {
            var spending = Mapper.Map<SpendingRequestEntity>(spendingService.FindById(id));
            AuthorizeHelper.AuthorizeUserGroupByResource(spending.ResourceId);
            var resource = resourcesService.FindById(spending.ResourceId);
            spending.Resources = resourcesService.GetResourcePackResources(resource.ResourcePackId);
            spending.ResourcePackId = resource.ResourcePackId;
            return PartialView(Mapper.Map<SpendingRequestEntity>(spending));
        }

        /// <summary>
        /// Изменяет определенный объект убытка
        /// </summary>
        /// <param name="spending">Сущность расхода</param>
        /// <returns>Перенаправляет на страницу просмотра убытка</returns>
        [HttpPost]
        public ActionResult EditSpending(SpendingRequestEntity spending)
        {
            if (ModelState.IsValid)
            {
                AuthorizeHelper.AuthorizeUserGroupByResource(spending.ResourceId);
                spendingService.Update(spending, Membership.GetUser().UserName);
                return RedirectToAction(
                    "ViewSpending",
                    new { id = spending.Id });
            }

            spending.Resources = resourcesService.GetResourcePackResources(spending.ResourcePackId);
            return PartialView(spending);
        }

        /// <summary>
        /// Страница добавления расхода на определенную дату 
        /// </summary>
        /// <param name="date">Дата добавления (оптимально)</param>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <returns>Перенаправляет на страницу просмотра бюджета на определенную дату</returns>
        [HttpGet]
        public ActionResult AddSpending(long resourcePackId, DateTime? date = null)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePackId);
            var resources = resourcesService.GetResourcePackResources(resourcePackId);
            var spending = new SpendingRequestEntity() { Resources = resources };
            spending.DateAndTime = date ?? DateTime.Today;
            return PartialView(spending);
        }

        /// <summary>

AntonenkoFamilyServerFinances/Controllers/Web/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using StructureMap;
using DataLayer.Models;
using BusinessLayer.Interfaces;
using DataLayer;

namespace AntonenkoFamilyServerFinances.Controllers.Web
{
    /// <summary>
    /// Контроллер страниц полнотекстового поиска
    /// </summary>
    [Authorize]
    public class SearchController : Controller
    {
        /// <summary>
        /// Сервис полнотекстового поиска
        /// </summary>
        private ISearchService searchService;

        /// <summary>
        /// Базовый конструктор
        /// </summary>
        public SearchController()
        {
            searchService = ObjectFactory.GetInstance<ISearchService>();
        }

        /// <summary>
        /// Страница поиска
        /// </summary>
        /// <returns>Возвращает представление страницы поиска</returns>
        [HttpGet]
        public ActionResult Index()
        {
            var model = new Dictionary<Type, bool>();
            var searchableTypes = searchService.GetSearchableModelsTypes();
            foreach (var type in searchableTypes)
            {
                model.Add(type, Constants.DefaultSearchTypes.Contains(type));
            }

            return View(model);
        }

        /// <summary>
        /// Страница результатов поиска
        /// </summary>
        /// <param name="config">Конфигурация поиска</param>
        /// <returns>Возвращает представление страницы результатов поиска</returns>
        [HttpPost]
        public ActionResult Search(SearchConfiguration config)
        {
            var result = searchService.Search(config);
            return PartialView("Index_Search", result);
        }
    }
}

AntonenkoFamilyServerFinances/Views/Shared/Header.cshtml
@using AFinances.PresentationLayer.Resources.Views
@using DataLayer
<div class="header">
        <div class="top-nav">
            <nav class="navbar navbar-fixed-top top-navigation">
                <h3>A Family Server Finances by Batareya16</h3>
				<div class="container">
				    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainNavBar">
                        @Header.Menu
                    </button>
                    </div>
                    <div class="collapse navbar-collapse" id="mainNavBar">
                        <ul class="nav navbar-nav">
						    <li>
                                <a href="@Url.Action("Index", "Home")"><i class="mdi mdi-home"></i>@Header.Home</a>
                            </li>
						    <li class="dropdown">
                                <a href="@Url.Action("Index", "Budget")" class="dropbtn"><i class="mdi mdi-cash-multiple"></i>@Header.Budget</a>
                                <div class="dropdown-content">
                                  <a href="#">Просмотр бюджета</a>
                                  <a href="#">Просмотр на сегодня</a>
                                  <a href="#">Просмотр на дату</a>
                                  <a href="#">Запланированные платежи</a>
                                </div>
                            </li>
						    <li class="dropdown">
                                <a href="@Url.Action("ViewMoneyTurnover", "Budget")" class="dropbtn"><i class="mdi mdi-chart-line"></i>@Header.MoneyTurnover</a>
                                <div class="dropdown-content">
                                  <a href="#">Просмотр прибыли/убытков</a>
                                  <a href="#">Добавить прибыль</a>
                                  <a href="#">Добавить убыток</a>
                                </div>
                            </li>
						    <li>
                                <a href="@Url.Action("Index", "Search")"><i class="mdi mdi-magnify"></i>@Header.Search</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Module")"><i class="mdi mdi-puzzle"></i>@Header.Modules</a>
                            </li>
                            <li>
                                <a href="@Constants.FakeLinkUrl" name="donateBtn"><i class="mdi mdi-cards-heart"></i>@Header.Donate</a>
                            </li>
						</ul>
                        <div style="float:right">
                        <ul class="nav navbar-nav">
						    <li>
                                <a href="@Url.Action("ViewCurrentAccount", "Account")" class="display-inline"><i class="mdi mdi-account"></i>@Membership.GetUser().UserName</a>
                            </li>
                             <li class="dropdown">
                                <a href="@Constants.FakeLinkUrl" name="selectCurrentResPack" class="display-inline dropbtn">
                                    <i class="mdi mdi-square-inc-cash"></i>
                                    <span name="currentResourcePackName"></span>&nbsp;
                                    (<span name="currentUserGroupName"></span>)
                                </a>
                                <div class="dropdown-content">
                                  <a href="@Constants.FakeLinkUrl" name="selectCurrentResPack">Выбрать текущий ресурспак</a>
                                  <a href="#">Просмотр текущего ресурспака</a>
                                </div>
                            </li>
                            <li>
                                <a class="display-inline" href="@Url.Action("LogOff", "Account")"><i class="mdi mdi-logout"></i>@Header.Logout</a>
                            </li>
                        </ul>
                        </div>
					</div>
			</nav>
    </div>
</div>
<script>
    setupCurrentResourcePack('@Common.EmptyCurrentResourcePack');
    $('[name=selectCurrentResPack]').click(function () {
        modalPanelFunctions.redirectModal('@Url.Action("ChangeCurrentResourcePack", "Account")');
        $("#@DataLayer.Constants.ModalPanelId").modal('show');
    });
    $('[name=donateBtn]').click(function () {
        modalPanelFunctions.redirectModal('@Url.Action("Donate", "Home")');
        $("#@DataLayer.Constants.ModalPanelId").modal('show');
    });
</script>

AntonenkoFamilyServerFinances/Views/Shared/ListPanel.cshtml
@model string[]
@using AFinances.PresentationLayer.Resources.Views
@{
 var header = Model[0];
 var listId = Model[1];
 var submitBtnId = Model[2];
 var havePagination = Model.Count() > 3;
}
<div class="base-form">
    <div class="base-form-heading">
        <div class="align-center panel-header">
            @if (havePagination)
            {
                <button class="btn btn-default display-inline" name="prevPanel">&lt;</button>
            }
            <h3 class="display-inline">@header</h3>
            @if (havePagination)
            {
                <button class="btn btn-default display-inline" name="nextPanel">&gt;</button>
            }
        </div>
        <div class="loader is-active inner-loader">
        </div>
        <ul class="list-group" id="@listId">
        </ul>
    </div>
    @if (!string.IsNullOrEmpty(submitBtnId))
    {
        <button class="btn1 btn-1 btn-1b form-control" id="@submitBtnId">@Common.Add</button>
    }
</div>

AntonenkoFamilyServerFinances/Views/Shared/MessageModalForm.cshtml
@model KeyValuePair<string, string>
<div id="MainContent">
@using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "MainContent", LoadingElementId = "Loader" }))
{
<div id="Loader" class="loader loader-default inner-loader"></div>
<div class="base-form">
    <div class="base-form-heading">
        <h3>@Model.Key</h3>
        <p>@Html.Raw(Model.Value)</p>
    </div>
</div>
}
</div>

AntonenkoFamilyServerFinances/Views/Shared/ModalPanel.cshtml
@model BusinessLayer.Entities.ModalPanelEntity
<div class="modal fade force-hidden" tabindex="-1" role="dialog" id="@Model.Id">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">@Model.Title</h5>
        <button type="button" class="close" aria-label="Close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        @Html.Partial(Model.PartialBodyViewName, Model.Model)
      </div>
    </div>
  </div>
</div>

<script>
    $('#@Model.Id').on('show.bs.modal', function (e) {
        $('#@Model.Id').removeClass('force-hidden');
    });

    var modalPanelFunctions = new ModalPanel();

    function showAndRedirectModal(url) {
        $('#@Model.Id').modal('show');
        modalPanelFunctions.redirectModal(url);
    }
</script>

AntonenkoFamilyServerFinances/Views/Shared/RemoveDialog.cshtml
@using AFinances.PresentationLayer.Resources.Views
<div id="dialog-confirm" title="">
<p>
    <span class="ui-icon ui-icon-alert dialog-margin"></span>
    <span class="dialog-confirm-body"></span>
</p>
</div>

<script>
    function confirmDialog() { }
    function toggleDialog(isOpen, body, title, buttonLbl) {
        var toggleAction = isOpen ? "open" : "close";
        $("#dialog-confirm .dialog-confirm-body").html(body || "@Common.AreYouReallyWantToRemove");
        $("#dialog-confirm").dialog("option", "title", title || "@Common.Remove?");
        $("#dialog-confirm").dialog(toggleAction);
        $("#dialog-confirm").dialog("option", "buttons", getDialogButtons(buttonLbl || "@Common.Remove"));
    }

    $("#dialog-confirm").dialog({
        resizable: false,
        height: "auto",
        width: 400,
        modal: true,
        autoOpen: false
    });

    function getDialogButtons(mainBtnLbl){
        var buttons = {};
        buttons[mainBtnLbl] = function () { confirmDialog(); };
        buttons["@Common.Cancel"] = function () { toggleDialog(false); };
        return buttons;
    }
</script>

AntonenkoFamilyServerFinances/Views/Shared/Scripts.cshtml
@using System
@using System.Text
@using System.IO
@using System.Web.Hosting

    <!-- Фоновое изображение -->
    <style>
        body
        {
            background: #67b26f; /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #67b26f, #4ca2cd); /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #67b26f, #4ca2cd); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: url("data:image/svg+xml;base64, @Convert.ToBase64String(Encoding.ASCII.GetBytes(File.ReadAllText(
                HostingEnvironment.MapPath("~/AppData/Images/background.svg"))))") no-repeat fixed 100% 100%; /* Main SVG Background */
            background-size: cover;
        }
    </style>

    <!-- Индикатор загрузки -->
    <script src="/AppData/Libs/spin-js/spin.js" type="text/javascript"></script>
    <script>
    var spinner = new Spinner().spin();
    document.getElementById("pageLoader").appendChild(spinner.el);
    </script>
    <!-- Стили -->
    <link rel="stylesheet" href="/AppData/Build/app.min.css" />
    <!-- Скрипты -->
    <script src="/AppData/Build/app.min.js" type="text/javascript"></script>

AntonenkoFamilyServerFinances/Views/Shared/Unauthorized.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>401</title>
</head>
<body>
    <div>
       <img src="~/Images/Cat.svg" width="200" height="200">
    </div>
</body>
</html>

AntonenkoFamilyServerFinances/Views/Shared/_BlankModalForm.cshtml
<div id="MainContent">
@using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "MainContent", LoadingElementId = "Loader" }))
{
    <div id="Loader" class="loader loader-default inner-loader"></div>
}
</div>

AntonenkoFamilyServerFinances/Views/Shared/_Layout-closeModal.cshtml
<div id="MainContent">
    @using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "MainContent", LoadingElementId = "Loader" }))
    {
        <div id="Loader" class="loader loader-default inner-loader"></div>
        <div class="base-form">
            <script>
                $('#@DataLayer.Constants.ModalPanelId').modal('hide');
            </script>
            @RenderBody()
        </div>
    }
</div>

AntonenkoFamilyServerFinances/Views/Shared/_Layout-minimal.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
@Html.Partial("Scripts")
@RenderBody()
</body>
</html>

AntonenkoFamilyServerFinances/Views/Shared/_Layout.cshtml
@using BusinessLayer.Entities
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div id="pageLoader" class="loader loader-default is-active">
    @Html.Partial("Scripts")
    </div>
    <div class="main-content">
        @Html.Partial("Header")
        <div class="container" hidden="true">
            @Html.Partial("RemoveDialog")
            @Html.Partial("ModalPanel",
                new ModalPanelEntity
                {
                    Id = DataLayer.Constants.ModalPanelId,
                    Model = null,
                    PartialBodyViewName = "_BlankModalForm",
                    Title = string.Empty
                })
            @RenderBody()
        </div>
    </div>
    <script type="text/javascript">
        $(".loader").each(function () {
            initializeSpinner(this);
        });

        $(document).ready(function () {
            $(".container>div").hide();
            $(".container").show();
            setDateTimePickerFormat('@DataLayer.Constants.DatePickerDateFormat');
            initializeDateTimePickers();
            $("#pageLoader").removeClass("is-active");
            $(".container>div").fadeIn(500);
        });
    </script>
</body>
</html>

AntonenkoFamilyServerFinances/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}