AntonenkoFamilyServerFinances/Controllers/Api/DataController.cs
using System.Web.Mvc;
using BusinessLayer.Interfaces;
using BusinessLayer.Entities;
using StructureMap;
using AFinances.PresentationLayer.Infrastructure;

namespace AntonenkoFamilyServerFinances.Controllers.Api
{
    /// <summary>
    /// API Контроллер для внешних приложений
    /// </summary>
    public class DataController : MobileController
    {
        /// <summary>
        /// Сервис бюджета
        /// </summary>
        private IBudgetService<IncomeRequestEntity> budgetService;

        /// <summary>
        /// Базовый контроллер
        /// </summary>
        public DataController()
        {
            budgetService = ObjectFactory.GetInstance<IBudgetService<IncomeRequestEntity>>();
        }

        /// <summary>
        /// Получает текущий бюджет ресурспаков в виде JSON
        /// </summary>
        /// <returns>Возвращает текущий бюджет ресурспаков в виде JSON</returns>
        public JsonResult GetCurrentBudgetJson(string encrTicket)
        {
            var principal = MobileAuthenticator.GetPrincipal(encrTicket);
            return AuthenticateRequest(encrTicket)
                ? Json(string.Empty)
                : Json(budgetService.GetBudgetResourcePacks(), JsonRequestBehavior.AllowGet);
        }

    }
}

AntonenkoFamilyServerFinances/Controllers/Web/ResourceController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using BusinessLayer.Interfaces;
using BusinessLayer.Infrastructure;
using StructureMap;
using AutoMapper;
using BusinessLayer.Entities;
using DataLayer.Models;
using System.Web.Security;
using AFinances.PresentationLayer.Resources.Views;
using CommonResource = AFinances.PresentationLayer.Resources.Views.Common;
using DataLayer;
using AFinances.PresentationLayer.Infrastructure;
using BusinessLayer.Entities.User;

namespace AntonenkoFamilyServerFinances.Controllers.Web
{
    /// <summary>
    /// Контроллер страниц управления ресурсами
    /// </summary>
    [Authorize]
    public class ResourceController : Controller
    {
        /// <summary>
        /// Сервис управления ресурспаками
        /// </summary>
        private IResourcePackService resourcePackService;

        /// <summary>
        /// Сервис управления группами пользователей
        /// </summary>
        private IUserGroupService userGroupService;

        /// <summary>
        /// Сервис управления ресурсами
        /// </summary>
        private IResourcesService resourcesService;

        /// <summary>
        /// Сервис управления типами ресурсов
        /// </summary>
        private IResourceTypeService resourceTypeService;

        /// <summary>
        /// Базовый конструктор
        /// </summary>
        public ResourceController()
        {
            resourcePackService = ObjectFactory.GetInstance<IResourcePackService>();
            resourcesService = ObjectFactory.GetInstance<IResourcesService>();
            userGroupService = ObjectFactory.GetInstance<IUserGroupService>();
            resourceTypeService = ObjectFactory.GetInstance<IResourceTypeService>();
        }

        /// <summary>
        /// Страница для просмотра деталей ресурспака
        /// </summary>
        /// <param name="id">Идентификатор ресурспака</param>
        /// <returns>Возвращает представление страницы просмотра деталей ресурспака</returns>
        [HttpGet]
        public ActionResult ViewResourcePack(long id)
        {
            return View(id);
        }

        /// <summary>
        /// Страница информации о ресурспаке
        /// </summary>
        /// <param name="resourcePack">Сущность ресурспака</param>
        /// <returns>Возвращает представление страницы информации о ресурспаке</returns>
        [HttpPost]
        public ActionResult GetResourcePackInfo(ResourcePackEntity resourcePack)
        {
            AuthorizeHelper.AuthorizeUserGroupByResourcePack(resourcePack.Id);
            var resourcePackEntity = Mapper.Map<ResourcePackEntity>(resourcePackService.FindByIdWithRelatedData(resourcePack.Id));
            return PartialView("ViewResourcePack_ResourcePack", resourcePackEntity);
        }
        
        /// <summary>
        /// Страница просмотра деталей ресурса
        /// </summary>
        /// <param name="id">Идентификатор ресурса</param>
        /// <returns>Возвращает представление страницы просмотра деталей ресурса</returns>
        [HttpGet]
        public ActionResult ViewResource(long id)
        {
            AuthorizeHelper.AuthorizeUserGroupByResource(id);
            var resource = Mapper.Map<ResourceEntity>(resourcesService.FindByIdWithRelatedData(id));
            return PartialView(resource);
        }

        /// <summary>
        /// Страница изменения ресурса
        /// </summary>
        /// <param name="resourceId">Сущность ресурса</param>
        /// <returns>Перенаправляет на страницу просмотра ресурса</returns>
        [HttpGet]
        public ActionResult EditResource(long resourceId)
        {
            AuthorizeHelper.AuthorizeResourcePackByResource(resourceId);
            var resource = Mapper.Map<ResourceEntity>(resourcesService.FindByIdWithRelatedData(resourceId));
            resource.ResourceTypes = resourceTypeService.GetForUserGroup(resource.ResourcePack.UserGroupId);
            return PartialView(resource);
        }

        /// <summary>
        /// Изменяет определенный ресурс в базе данных
        /// </summary>
        /// <param name="resource">Сущность ресурса</param>
        /// <returns>Перенаправляет на страницу просмотра ресурса</returns>
        [HttpPost]
        public ActionResult EditResource(ResourceEntity resource)
        {
            AuthorizeHelper.AuthorizeResourcePackByResource(resource.Id);
            AuthorizeHelper.AuthorizeResourceType(resource.ResourceTypeId);
            if (ModelState.IsValid)
            {
                resourcesService.Update(resource, Membership.GetUser().UserName);
                return RedirectToAction("ViewResource", new { resource.Id });
            }

            var dbResource = resourcesService.FindByIdWithRelatedData(resource.Id);
            resource.ResourceTypes = resourceTypeService.GetForUserGroup(dbResource.ResourcePack.UserGroupId);
            return PartialView(resource);
        }

        /// <summary>
        /// Страница добавления ресурса
        /// </summary>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>
        /// <returns>Возврашает представление страницы добавления ресурса</returns>
        [HttpGet]
        public ActionResult AddResource(long? resourcePackId)
        {
            var resource = new ResourceEntity();
            if (resourcePackId.HasValue)
            {
                AuthorizeHelper.AuthorizeResourcePack(resourcePackId.Value);
                resource.ResourcePack = Mapper.Map<ResourcePackEntity>(resourcePackService.FindById(resourcePackId.Value));
                resource.ResourcePackId = resource.ResourcePack.Id;
                resource.ResourceTypes = resourceTypeService.GetForUserGroup(resource.ResourcePack.UserGroupId);
            }
            else
            {
                var userName = Membership.GetUser().UserName;
                resource.ResourcePacks =
                    Mapper.Map<IEnumerable<ResourcePackEntity>>(resourcePackService.GetForCurrentUserGroup(userName));
                resource.ResourceTypes = resourceTypeService.GetForCurrentUserGroup(userName);
            }
            return PartialView(resource);
        }

        /// <summary>
        /// Добавляет ресурс в базу данных
        /// </summary>
        /// <param name="resource">Сущность ресурса</param>
        /// <returns>Перенаправляет на страницу просмотра ресурса</returns>
        [HttpPost]
        public ActionResult AddResource(ResourceEntity resource)
        {
            AuthorizeHelper.AuthorizeResourcePackByResource(resource);
            AuthorizeHelper.AuthorizeResourceType(resource.ResourceTypeId);
            if (ModelState.IsValid)
            {
                var id = resourcesService.Add(resource, Membership.GetUser().UserName);
                return RedirectToAction("ViewResource", new { id });
            }

            resource.ResourcePack =
                Mapper.Map<ResourcePackEntity>(resourcePackService.FindById(resource.ResourcePackId));
            resource.ResourceTypes = resourceTypeService.GetForUserGroup(resource.ResourcePack.UserGroupId);
            return PartialView(resource);
        }

        /// <summary>
        /// Удаляет ресурс из базы данных
        /// </summary>
        /// <param name="id">Идентификатор ресурса</param>
        /// <returns>Перенаправляет на пустую страницу модального окна</returns>
        [HttpGet]
        public ActionResult RemoveResource(long id)
        {
            AuthorizeHelper.AuthorizeResourcePackByResource(id);
            resourcesService.Remove(id, Membership.GetUser().UserName);
            return PartialView("_BlankModalForm");
        }

        /// <summary>
        /// Страница добавления ресурспака
        /// </summary>
        /// <param name="userGroupId">Идентификатор группы пользователей (опционально)</param>
        /// <returns>Возвращает представление страницы добавления ресурспака</returns>
        [HttpGet]
        public ActionResult AddResourcePack(long? userGroupId)
        {
            var resourcePackEntity = new ResourcePackEntity();
            if (userGroupId.HasValue)
            {
                AuthorizeHelper.AuthorizeUserGroup(userGroupId.Value);
                resourcePackEntity.UserGroupId = userGroupId.Value;
                resourcePackEntity.UserGroup =
                    Mapper.Map<UserGroupEntity>(userGroupService.FindById(userGroupId.Value));
            }

            return PartialView(resourcePackEntity);
        }

        /// <summary>
        /// Добавляет ресурспак в базу данных
        /// </summary>
        /// <param name="resourcePack">Сущность ресурспака</param>
        /// <returns>Перенаправляет на страницу сообщения об успешном создании ресурспака</returns>
        [HttpPost]
        public ActionResult AddResourcePack(ResourcePackEntity resourcePack)
        {
            if (ModelState.IsValid)
            {
                AuthorizeHelper.AuthorizeResourcePack(resourcePack);
                var id = resourcePackService.Add(resourcePack, Membership.GetUser().UserName);
                return PartialView("MessageModalForm", new KeyValuePair<string, string>(
                            Titles.AddResourcePack,
                            string.Format(
                                CommonResource.ResourcePackCreatedSuccsessfully,
                                CommonHelper.GenerateLink(Url.Action("ViewResourcePack", new { id }), CommonResource.ResourcePack))));
            }

            return PartialView(resourcePack);
        }

        /// <summary>
        /// Страница изменения ресурспака
        /// </summary>
        /// <param name="resourcePackId">Идентификатор ресурспака</param>

AntonenkoFamilyServerFinances/Controllers/Web/UserGroupController.cs
using System.Web.Mvc;
using System.Linq;
using BusinessLayer.Entities.User;
using BusinessLayer.Interfaces;
using StructureMap;
using System.Web.Security;
using BusinessLayer.Infrastructure;
using BusinessLayer.Entities;
using BusinessLayer.Resources;
using AFinances.PresentationLayer.Infrastructure;

namespace DataLayer.Controllers.Web
{
    /// <summary>
    /// Контроллер страниц управления группами пользователей
    /// </summary>
    [Authorize]
    public class UserGroupController : Controller
    {
        /// <summary>
        /// Сервис группы пользователей
        /// </summary>
        private IUserGroupService userGroupService;

        /// <summary>
        /// Стандартный конструктор
        /// </summary>
        public UserGroupController()
        {
            userGroupService = ObjectFactory.GetInstance<IUserGroupService>();
        }

        /// <summary>
        /// Страница добавления группы пользователей
        /// </summary>
        /// <returns>Перенаправляет на страницу добавления группы пользователей</returns>
        [HttpGet]
        public ActionResult AddUserGroup()
        {
            var userGroup = new UserGroupEntity();
            return PartialView(userGroup);
        }

        /// <summary>
        /// Создает группу пользователей
        /// </summary>
        /// <param name="userGroup">Сущность группы пользователей</param>
        /// <returns>Перенаправляет на страницу просмотра группы пользователей</returns>
        [HttpPost]
        public ActionResult AddUserGroup(UserGroupEntity userGroup)
        {
            if (ModelState.IsValid)
            {
                if (userGroup.Users.All(x => ValidationHelper.IsValid<BaseUserEntity>(x)))
                {
                    var id = userGroupService.Add(userGroup, Membership.GetUser().UserName);
                    return RedirectToAction("ViewUserGroup", new { id });
                }
                else
                {
                    ModelState.AddModelError(
                        CommonHelper.nameof(() => userGroup.Users),
                        string.Format(Errors.IncorrectFormat, Resources.Models.Account.UserName));
                }
            }

            return PartialView(userGroup);
        }

        /// <summary>
        /// Страница просмотра группы пользователей
        /// </summary>
        /// <param name="id">Идентификатор группы пользователей</param>
        /// <returns>Возвращает страницу просмотра группы пользователей</returns>
        [HttpGet]
        public ActionResult ViewUserGroup(long id)
        {
            AuthorizeHelper.AuthorizeUserGroup(id);
            var userGroup = userGroupService.FindByIdWithRelatedUsers(id);
            return PartialView(userGroup);
        }

        [HttpGet]
        public ActionResult EditUserGroup(long id)
        {
            AuthorizeHelper.CheckUserGroupOwner(id);
            var userGroup = userGroupService.FindByIdWithRelatedUsers(id);
            return PartialView(userGroup);
        }

        /// <summary>
        /// Удаляет группу пользователей из базы данных
        /// </summary>
        /// <param name="id">Идентификатор группы пользователя</param>
        /// <returns>Перенаправляет на пустую страницу модального окна</returns>
        [HttpGet]
        public ActionResult RemoveUserGroup(long id)
        {
            AuthorizeHelper.CheckUserGroupOwner(id);
            userGroupService.Remove(id, Membership.GetUser().UserName);
            return PartialView("_BlankModalForm");
        }

        /// <summary>
        /// Изменяет группу пользователей
        /// </summary>
        /// <param name="userGroup">Сущность группы пользователей</param>
        /// <returns>Перенаправляет на страницу просмотра группы пользователей</returns>
        [HttpPost]
        public ActionResult EditUserGroup(UserGroupEntity userGroup)
        {
            if (ModelState.IsValid)
            {
                AuthorizeHelper.CheckUserGroupOwner(userGroup.Id);
                if (userGroup.Users.All(x => ValidationHelper.IsValid<BaseUserEntity>(x)))
                {
                    userGroupService.Update(userGroup, Membership.GetUser().UserName);
                    return RedirectToAction("ViewUserGroup", new { id = userGroup.Id });
                }
                else
                {
                    ModelState.AddModelError(
                        CommonHelper.nameof(() => userGroup.Users),
                        string.Format(Errors.IncorrectFormat, Resources.Models.Account.UserName));
                }
            }

            return PartialView(userGroup);
        }

        [HttpPost]
        public PartialViewResult GetUserGroups(int userGroupsPage)
        {
            return PartialView(userGroupService.GetPageForUser(userGroupsPage, Membership.GetUser().UserName));
        }
    }
}

AntonenkoFamilyServerFinances/Views/UserGroup/AddManageUserGroupBase.cshtml
@using AFinances.PresentationLayer.Resources.Views
@using AFinances.PresentationLayer.Resources.Views.UserGroup
@using BusinessLayer.Infrastructure
@using BusinessLayer.Entities.User
@using DataLayer
@model UserGroupEntity
<div id="AddEditUserGroupBase">
    @using (Ajax.BeginForm(
        null,
        null,
        null,
        new AjaxOptions
        {
            UpdateTargetId = "AddEditUserGroupBase",
            LoadingElementId = "Loader",
            OnBegin = "modalPanelFunctions.toggleForm(true)",
            OnSuccess = "modalPanelFunctions.toggleForm(false)"
        },
        new { autocomplete = "off" }))
    {
        <div id="Loader" class="loader loader-default inner-loader"></div>
        <input autocomplete="false" type="text" style="display:none" />
        <div class="base-form">
            <div class="base-form-heading">
                <h3>@ViewBag.Title</h3>
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.UsersJson)
                @Html.ValidationSummary(true)

                <div class="editor-label">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
                <br />
                <div class="editor-field">
                    <label>
                    @Html.LabelFor(model => model.Private)
                    <input type="checkbox" data-toggle="toggle" name="@CommonHelper.nameof(() => Model.Private)" />
                    @Html.ValidationMessageFor(model => model.Private)
                    </label>
                </div>
                <br />
                <div class="editor-label">
                    @Html.Label(@AddManageUserGroup.AddUsers)
                </div>
                <div class="editor-field">
                    @Html.TextBox("UserSearch", string.Empty, new { @class = "form-control", placeholder = AddManageUserGroup.EnterUserName})
                        <div class="dropdown-content user-search-results">
                        </div>
                </div>
                @Html.ValidationMessageFor(model => model.Users)
                <table class="table" id="seletedUsersTable">
                    <colgroup>
                        <col width="90%"/>
                        <col width="10%"/>
                    </colgroup>
                    <tbody>
                    @foreach (var user in Model.Users)
                    {
                        <tr>
                            <td class="selected-user">
                                @user.UserName
                            </td>
                            <td>
                                <button type="button" class="btn btn-danger remove-found-user">
                                    <i class="mdi mdi-delete"></i>
                                </button>
                            </td>
                        </tr> 
                    }
                    </tbody>
                </table>
                <br />
                <button type="submit" class="btn1 btn-1 btn-1b form-control">@ViewBag.AcceptBtnName</button>
            </div>
        </div>
        <script type="text/basis-template" id="selected-user-template">
            <tr>
                <td class="selected-user">
                    {username}
                </td>
                <td>
                    <button type="button" class="btn btn-danger remove-found-user">
                        <i class="mdi mdi-delete"></i>
                    </button>
                </td>
            </tr>
        </script>
        <script>
            modalPanelFunctions.initializeModal();
            var timeoutID = null;
            var userGroupFunctions = new ManageUserGroup("@Url.Action("SearchUsersFuzzy", "Data")");
            userGroupFunctions.bindRemoveUserButton(userGroupFunctions);

            $('#UserSearch').on("keyup", function(e) {
                clearTimeout(timeoutID);
                timeoutID = setTimeout(() => userGroupFunctions.findUsers(e.target.value, true), 500);
            });

            var $privateToggle = $('[name=@CommonHelper.nameof(() => Model.Private)]');
            $privateToggle.bootstrapToggle({
                on: '@Common.Yes',
                off: '@Common.No'
            });
            $privateToggle.prop('checked', getBool("@Model.Private")).change();

            $('#AddEditUserGroupBase form').submit(function () {
                if ($('#AddEditUserGroupBase form').valid()) {
                    userGroupFunctions.applySelectedUsers();
                    fixToggleValue($privateToggle);
                    $('#AddEditUserGroupBase form').validate().cancelSubmit = true;
                }
            });
        </script>
    }
</div>

AntonenkoFamilyServerFinances/Views/UserGroup/AddUserGroup.cshtml
@using AFinances.PresentationLayer.Resources.Views;
@{
    Layout = null;
    ViewBag.Title = Titles.AddUserGroup;
    ViewBag.AcceptBtnName = Common.Add;
}
@model BusinessLayer.Entities.User.UserGroupEntity
@Html.Partial("AddManageUserGroupBase")

AntonenkoFamilyServerFinances/Views/UserGroup/EditUserGroup.cshtml
@using AFinances.PresentationLayer.Resources.Views;
@{
    Layout = null;
    ViewBag.Title = Titles.EditUserGroup;
    ViewBag.AcceptBtnName = Common.Edit;
}
@model BusinessLayer.Entities.User.UserGroupEntity
@Html.Partial("AddManageUserGroupBase")

AntonenkoFamilyServerFinances/Views/UserGroup/GetUserGroups.cshtml
@using BusinessLayer.Entities.User
@using DataLayer
@model IEnumerable<UserGroupEntity>
@foreach (var item in Model)
{
    <li class='list-group-item'>
        <p>
            <a href="@Constants.FakeLinkUrl" class="modal-redirect" url="@Url.Action("ViewUserGroup","UserGroup")/@item.Id">
                <b>@item.Name</b>&nbsp;(@item.OwnerUsername)
            </a>
        </p>
    </li>
}

AntonenkoFamilyServerFinances/Views/UserGroup/ViewUserGroup.cshtml
@using AFinances.PresentationLayer.Infrastructure
@using AFinances.PresentationLayer.Resources.Views
@using AFinances.PresentationLayer.Resources.Views.UserGroup
@using BusinessLayer.Infrastructure
@using BusinessLayer.Entities
@using DataLayer
@{
    ViewBag.Title = Titles.ViewUserGroup;
    Layout = null;
}
@model BusinessLayer.Entities.User.UserGroupEntity

<div id="ViewUserGroup">
    @using (Ajax.BeginForm(
        null,
        null,
        null,
        new AjaxOptions
        {
            UpdateTargetId = "ViewUserGroup",
            LoadingElementId = "Loader",
            OnBegin = "modalPanelFunctions.toggleForm(true)",
            OnSuccess = "modalPanelFunctions.toggleForm(false)"
        },
        new { autocomplete = "off" }))
    {
        @Html.HiddenFor(x => x.Id)
        <div id="Loader" class="loader loader-default inner-loader"></div>
        <div class="base-form">
            <div class="base-form-heading">
                <h3>@ViewBag.Title</h3>
                <label class="append-colon">@Html.LabelFor(model => model.Name)</label>
                @Model.Name
                <hr />
                <label class="append-colon">@Html.LabelFor(x => x.OwnerUsername)</label>
                @Model.OwnerUsername
                <hr />
                <label class="append-colon">@Html.LabelFor(x => x.Private)</label>
                @(Model.Private ? Common.Yes : Common.No)
                <hr />
                <div class="editor-label">
                    @Html.Label(ViewUserGroup.GroupUsers)
                </div>
                <ul class="list-group modal-panel-list">
                    @foreach (var item in Model.Users)
                    {
		                <li class="list-group-item">@item.UserName</li>
                    }
                </ul>
                <br />
                <div class="editor-label">
                    @Html.Label(ViewUserGroup.GroupResourcePacks)
                </div>
                <ul class="list-group modal-panel-list">
                    @foreach (var item in Model.ResourcePacks)
                    {
		                <li class="list-group-item">@item.Name</li>
                    }
                </ul>
                <br />
                <div class="row">
                @try{
                    AuthorizeHelper.AuthorizeResourcePack(new ResourcePackEntity() { UserGroup = Model, UserGroupId = Model.Id });
                    <div class="col-xs-4">
                        <button type="button" class="btn1 btn-1 btn-1b form-control modal-redirect" url="@Url.Action("AddResourcePack", "Resource", new { userGroupId = Model.Id })">@Titles.AddResourcePack</button>
                    </div>
                }
                catch{}
                        
                @if (Membership.GetUser().UserName == Model.OwnerUsername)
                {
                    <div class="col-xs-4">
                        <button type="button" class="btn1 btn-1 btn-1b form-control modal-redirect" url="@Url.Action("EditUserGroup", new { id = Model.Id })">@Common.Edit</button>
                    </div>
                    <div class="col-xs-4">
                        <button type="button" class="btn1 btn-1 btn-1b form-control modal-redirect" id="RemoveUserGroup">@Common.Remove</button>
                    </div>
                }
                </div>
            </div>
        </div>
        <script>
            modalPanelFunctions.initializeModal();
            
            $("#RemoveUserGroup").click(function () { toggleDialog(true); });
            function confirmDialog() {
                toggleDialog(false);
                modalPanelFunctions.redirectModal("@Url.Action("RemoveUserGroup", "UserGroup", new { id = Model.Id })");
            }
        </script>
    }
</div>